"""LangGraph 节点函数。

每个节点签名: async def node_*(state: OrchestratorState, deps: NodeDeps) -> dict
返回 dict 是 LangGraph 增量 update (会自动 merge 进 state)。

step_executor 节点单独在 graph.py 里以循环子图实现, 不放这里。
verify 节点也在 graph.py 里 (调 bash 跑 lint/test, 用 verify_fixer 修复)。
pr_creator 暂用 mock URL, 等 mcp-server-github 接入后替换。
"""

from dataclasses import dataclass
from typing import Any

from app.codemap.scanner import CodeMap
from app.skills.registry import SkillRegistry
from app.agents.skill_router import SkillRouter
from app.agents.slot_check import SlotChecker
from app.agents.clarify_reflexion import ClarifyReflexion
from app.orchestrator.state import OrchestratorState


@dataclass
class NodeDeps:
    registry: SkillRegistry
    codemap: CodeMap
    llm: Any  # LLMClient


async def node_clarify(state: OrchestratorState, deps: NodeDeps) -> dict:
    """Reflexion 澄清: 输出 understanding + questions"""
    clarify = ClarifyReflexion(deps.llm)
    result = await clarify.clarify(state["raw_intent"])
    return {
        "reflexion_critique": result.understanding,
        "pending_questions": list(result.questions),
    }


async def node_router(state: OrchestratorState, deps: NodeDeps) -> dict:
    """Skill 路由"""
    router = SkillRouter(deps.registry)
    result = router.route(state["raw_intent"])
    return {
        "matched_skill": result.top1.skill_name,
        "skill_confidence": result.top1.confidence,
    }


async def node_slot_check(state: OrchestratorState, deps: NodeDeps) -> dict:
    """槽位检查 + 默认值填充, 追加问题到 pending_questions"""
    skill = deps.registry.business(state["matched_skill"])
    checker = SlotChecker()
    result = checker.check(skill, state["pm_answers"])
    return {
        "filled_params": result.filled,
        "pending_questions": list(state["pending_questions"]) + list(result.questions),
    }


async def node_plan_builder(state: OrchestratorState, deps: NodeDeps) -> dict:
    """Skill.plan() 展开成 step dict 列表"""
    skill = deps.registry.business(state["matched_skill"])
    steps = skill.plan(state["filled_params"])
    return {"plan_steps": [s.model_dump() for s in steps]}


async def node_pr_creator(state: OrchestratorState, deps: NodeDeps) -> dict:
    """提 PR。

    若 env CODEWIZ_HEAD_REPO 设置 → 用 PrCreator 真 branch + commit + format-patch
      (默认 dry_run=True 不实推, CODEWIZ_PR_DRY_RUN=false 才真推 gh pr create)
    否则 → 返 mock URL (向后兼容, 演示安全)。
    """
    import os

    branch = state["branch_name"]
    skill = state["matched_skill"]
    head_repo = os.environ.get("CODEWIZ_HEAD_REPO")

    if not head_repo:
        return {
            "pr_url": (
                f"https://github.com/codewiz-bot/conduit/pull/mock-{skill}"
                f"?branch={branch}"
            ),
        }

    # 真 PR 路径
    from app.orchestrator.pr_creator import PrCreator

    dry_run = os.environ.get("CODEWIZ_PR_DRY_RUN", "true").lower() != "false"
    creator = PrCreator(
        repo_root=state["repo_clone_path"],
        head_repo=head_repo,
        dry_run=dry_run,
    )
    info = creator.stage_branch_commit(
        skill_name=skill,
        summary=f"feat({skill}): generated by CodeWiz ExploreEditAgent",
    )
    pr_url = creator.push_and_pr(
        info["branch"],
        title=f"feat: {skill}",
        body=(
            f"Skill: {skill}\n"
            f"Generated by CodeWiz ExploreEditAgent.\n\n"
            f"Acceptance results: "
            f"{sum(1 for r in state.get('acceptance_results', []) if r.get('ok'))}/"
            f"{len(state.get('acceptance_results', []))} passed.\n"
            f"Trace id: {state.get('trace_id')}"
        ),
    )
    return {"pr_url": pr_url}


# --- v3 §C Step 2: contract 路径节点 ---


async def node_load_contract(state: OrchestratorState, deps: NodeDeps) -> dict:
    """从 registry 拿 skill, 调 contract(filled_params)。

    返 dict (model_dump) 给 LangGraph state, 兼容 PostgresSaver 序列化。
    返 None 表示该 Skill 走旧 plan() 路径 (graph.py 的 conditional 据此分叉)。
    """
    skill = deps.registry.business(state["matched_skill"])
    contract = skill.contract(state.get("filled_params", {}))
    if contract is None:
        return {"skill_contract": None}
    return {"skill_contract": contract.model_dump()}


async def node_explore_edit(state: OrchestratorState, deps: NodeDeps) -> dict:
    """跑 ExploreEditAgent: contract → 探索 + 编辑 + acceptance 验收."""
    from app.agents.explore_edit_agent import ExploreEditAgent
    from app.skills.contract import SkillContract
    from app.harness.tools import get_tools

    contract_dict = state["skill_contract"]
    if contract_dict is None:
        # 防御: 不应该到这里 (graph 已 conditional 分叉)
        return {"acceptance_results": [], "pending_diff": []}

    contract = SkillContract(**contract_dict)
    agent = ExploreEditAgent(
        llm=deps.llm,
        repo_root=state["repo_clone_path"],
        tools_schema=get_tools(),
    )
    result = await agent.run(contract)
    return {
        "acceptance_results": [r.model_dump() for r in result.acceptance],
        "pending_diff": list(result.diff_files),
    }


async def node_trace(state: OrchestratorState, deps: NodeDeps) -> dict:
    """v3 §E Task 23 占位: 暂只分配/保留 trace_id, 真 JSONL 落盘等 trace.py 接入."""
    import uuid

    return {"trace_id": state.get("trace_id") or uuid.uuid4().hex[:12]}
